### ISSUE TITLE
上传失败: {"error":"token not specified"}

### ISSUE THREAD

**Issue by pengwei1024** [icattlecoder/7niu#2]
一直报错上传失败，求解决！！！！

``` xml
{"error":"token not specified"}
```

**Comment by mqliutie** [comment]
我的是bad token,不知道为啥

**Comment by icattlecoder** [comment]
需要自行搭建php环境运行，修改accessKey和secretKey以及bucket,位置：
https://github.com/icattlecoder/7niu/blob/master/index.php#L3

**Comment by mqliutie** [comment]
嗯,昨天PHP环境没弄,,,
